######################################################################
# Automatically generated by qmake (3.1) Sat Jan 18 21:39:33 2025
######################################################################

TEMPLATE = app
TARGET = package-tracker
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = PackageTracker
TEMPLATE = app

SOURCES += main.cpp \
           mainwindow.cpp

HEADERS += mainwindow.h

# Specify Homebrew's Qt installation path
QMAKE_MACOSX_DEPLOYMENT_TARGET = 14.0
QMAKE_APPLE_DEVICE_ARCHS = arm64
QMAKE_LFLAGS += -F/opt/homebrew/lib
INCLUDEPATH += /opt/homebrew/include
LIBS += -F/opt/homebrew/lib -framework QtCore -framework QtGui -framework QtWidgets

# Silence SDK version warning
CONFIG += sdk_no_version_check
